'''
Find clumps

Sample Input:
CGGACTCGACAGATGTGAAGAACGACAATGTGAAGACTCGACACGACAGAGTGAAGAGAAGAGGAAACATTGTAA
5 50 4

Sample Output:
CGACA GAAGA
'''

# text = input('Enter text: ')
# text = 'TTCACCGTTCATGAGCTTATTAATGAAGCCAGACGGTTTGGCCATGAAATTTGAGGTCACCACCGCTTCATTGTCGGGCTCCTGTTCAGTTCAATACTAAAAAGTTCCTTGGGTGCCCCGCGCCCCGGTGTGCCCCGCCCGCGAGGTCGCCTATGCATTGATTCTTCATGATTACCTCGTTCCCGTACACGTAGATCACGAGCTTGCTTACCCCCCTACCCGATCGTGCAAGACATAGTTAGGAGAAAACCTACCGATAGTAGTGGGCTGTAGTGGGCTGCTACGCAATAGGACCGCAATTGCTACACTGCGCATCGGGTAGTGTGTCAAACGACAGATGTTCGAGACGCGCGACAGGGAACTTATCTCAGTTCCGCCCTAATACAAACTAAAGTTCTGCTACACTCGCGAACACTGCATTCGTTCCGGGACACCCTGGTTATCCAAAGCCCTGTAGAGGTATGCCGCACGATCGATACGGCGGTGCCATGGGTGGGCCAATGTAAACACAATTCAGGGTCCCACTCACCCTGTCGCTTATTTGGAGAGGCGACTAGGCGACGGGACGGAAGATCACTGGCTTATCGAGGTTCTATTGGTGGAATTGTGTATCCCTGACAGCCGGAAACACTTTCAGCGAGCAGATATTTTCTCCCATGGTTTGCTAGTACGGTTGCGCCTATAAGCATCTCGAGGTGGAGGAGGATATACGGAATCCGGGATGGACACGGAGGATACGCAGGCCGGATTCATCCTTGGGCCATCTTTGTGCACTAACCGTATGCTAAAAGGTTTGCCTGCGCGCCGCAAAGAGTGACGTGACAGCACCGTAGCGCGCGGGGCCTCGTGCGGCGGTCGTGGGTTATGAAAATTTCCAGGCCGAATGTATCTGCGGCGTCGAAGACGGCACTTCTCATTTACTCTGACGGAGTGGACGGTTATAATTTGTGCCGATAACCTGCCGTGCCGATAAGTACATATAGAGGGAGGCGGGACTCTATCTGGCTTCCATTTCAGATTCGGCAGCTTCGGCAGCTGCAGCTGTGCGGCGTACACTAGCACTCGGTGAGACGTGAGACGAGACGATGAGACGACAGCACCTGTATCGGGGGTCCAGTTGTTGGCTCGTTCAGTTAGCGGTCGCTCAGCGTTCATCTCATCAGGGATCAGGGCCTGGTCGAGACTCCGGGCCAGTCCCATGCGTTGGCGGCGCACCCGCTTGAGACGCCTCATGCGTGTCGTCGTGGCATGAGCATCTATGAGCATCGCATCGTCTGAGGTCCCACTAAGCGTCTAAGTAATATGCCAGTACGGACCCCCGCTACGAGCCTAGGAGCCCGCGAGCCTAGGGGAGGGCGGCGGGGGGAGCACACTACTCCGATATGACAGCTTTGGCACATTGAGGATGTCGCAGTATGGTTACGTTGGCACGCGCGACAAGTGCAAATCTCCTACACTCCTAGGCAGAGGCATCCCGCCTATACATGATTAAAATACCCAGCAAGATGGTCTCTGGGGCAGATGGTCTTCTAATCGTAACGGACATACGCCGTATAGCTCATATGTACCCACCTGACAGGTTGTAAGATGCACGTCTACGTCTACCGCTACCGGTAAACAGGGTTGAAATGGGCGAAGCGAGGGGGGGCGAAGCTTTGTATCCCGAAGCACTTTTCGATGCGGCAGGTCCCGGTAAACCTACGATATATCAATGGCGTAATAAGAATAGCTCTGATCTTTTGTCCACTCCCGGCCAATCCAGAAAGTTAAGGCGTGGCTCCGTAAATGTTGGACCAACCAAGCAGTACCCCAAGCAGTATATATATATTACGCCTGAGAAAAATGAGAAAAATGAGAAAAATGAGAAAAATGAGAAAAATGA'
with open('E_coli.txt', 'r') as file:
    text = file.read()
k = int(input('Enter k: '))
L = int(input('Enter L: '))
t = int(input('Enter t: '))

n = len(text)
pattern_to_freq = {}

def generate_kmer_freq_map(text, k):
    for i in range(n - k+1):
        kmer = text[i:i+k]
        if kmer in pattern_to_freq:
            pattern_to_freq[kmer].append(i)
        else:
            pattern_to_freq[kmer] = [i]

generate_kmer_freq_map(text, k)

clumps = []
for kmer, indices in pattern_to_freq.items():
    if len(indices) >= t: # occurs t times
        adjustedL = L-k
        for i in range(len(indices) - t+1):
            x = indices[i]
            y = indices[i + t-1] 
            if y - x <= adjustedL:
                if kmer not in clumps:
                    clumps.append(kmer)

print(len(clumps)) 
